import = [
    "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

[font]
size = 10

[font.normal]
family = "Hack Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0
